import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "../components/Weather";
import Spinner from "../components/Spinner";

export default function Home() {
  const [city, setCity] = useState("");
  //const [country, setCountry] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  console.log(city);
  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity("");
    //setCountry("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <>
        <div>
          <Head>
            <title>Weathter-Next app</title>
            <meta
              name="description"
              content="Generated by create Nextapp"
            ></meta>
            <link rel="icon" href="/favicon.ico" />{" "}
          </Head>
          {/*overlay*/}
          <div className="absolute bg-black/40 z-[1] top-0 left-0 right-0 bottom-0" />
          <Image
            src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=775&q=80"
            layout="fill"
            alt=""
            className="object-cover"
          />
          {/*search*/}
          <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white  z-10">
            <form
              onSubmit={fetchWeather}
              className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl"
            >
              <div className="">
                <input
                  onChange={(e) => setCity(e.target.value)}
                  type="text"
                  placeholder="Search city"
                  className="w-full bg-transparent border-none text-white focus:outline-none text-2xl"
                />
              </div>
              <button onClick={fetchWeather}>
                {" "}
                <BsSearch size={20} />
              </button>
            </form>
          </div>
          {/*search weather*/}
          {weather.main && <Weather data={weather} />}
          <button onClick={fetchWeather}>button</button>
        </div>
      </>
    );
  }
}
